// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keixjpxsvaxklharsggs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaXhqcHhzdmF4a2xoYXJzZ2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTE5MTcsImV4cCI6MjA2ODAyNzkxN30.RBgHWpgxoP44ZIsWtn7jkWRmfwMnMhWRA7V4VJ4Gajk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});